#!/usr/bin/env bash
# Transfers a file from our client to a server

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp  -o StrictHostKeyChecking=no -i~/.ssh/authorized_keys somepage.html ubuntu@100.25.2.67:~/
fi

