#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

#Updating and installing Nginx
apt-get update
apt-get install -y nginx

# Allow permission
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Creates the /etc/nginx/html directory
mkdir /etc/nginx/html
#  creates an  index.html file inside the /etc/nginx/html directory contain hello world
echo "Hello World!" > /etc/nginx/html/index.html
# Sets Nginx to listen on port 80 and serve files from the /etc/nginx/html directory.
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Display script completion message
echo "Nginx installation and configuration completed."

# Create a configuration file for the redirection
echo "server {
    listen      80;
    listen      [::]:80;
    root        /etc/nginx/html;
    index       index.html index.htm;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }

}" | sudo tee /etc/nginx/sites-available/default

# Enable the new site configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Test nginx configuration and reload
sudo nginx -t
sudo service nginx reload

echo -e "\nCompleted.\n"
