#!/usr/bin/env bash
# configure nginx to listen on port 80

#Configure listening on port 80 of all the server’s active IPv4 IPs
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
